package com.Example.ConModule.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.Example.ConModule.model.ModuleModel;
import com.Example.ConModule.repository.ModuleRepo;

public class ModuleController {
	@Controller    // This means that this class is a Controller
	@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
	public class MainController {
		@Autowired // This means to get the bean called userRepository
		           // Which is auto-generated by Spring, we will use it to handle the data
		private ModuleRepo moduleRepository;

		@GetMapping(path="/add") // Map ONLY GET Requests
		public @ResponseBody String addNewUser (@RequestParam String name
				, @RequestParam String email) {
			
			
			ModuleModel n = new ModuleModel();
			n.setName(name);
			n.setEmail(email);
			moduleRepository.save(n);
			return "Saved";
		}

		@GetMapping(path="/all")
		public @ResponseBody Iterable<ModuleModel> getAllUsers() {
			// This returns a JSON or XML with the users
			return moduleRepository.findAll();
		}

	}}
